name: helpful
description: A helpful Dart library.
version: 0.1.0
repository: https://github.com/mosuem/helpful

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.6
